// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/customer/orderaction/order_action.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/customer/orderaction/order_action.go -destination=internal/domain/customer/orderaction/order_action_mock.go -package=orderaction
//

// Package orderaction is a generated GoMock package.
package orderaction

import (
	context "context"
	reflect "reflect"
	time "time"

	messageprocessor "github.com/Mikhalevich/tg-coffee-shop-bot/internal/domain/messageprocessor"
	button "github.com/Mikhalevich/tg-coffee-shop-bot/internal/domain/messageprocessor/button"
	msginfo "github.com/Mikhalevich/tg-coffee-shop-bot/internal/domain/port/msginfo"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageSender is a mock of MessageSender interface.
type MockMessageSender struct {
	ctrl     *gomock.Controller
	recorder *MockMessageSenderMockRecorder
	isgomock struct{}
}

// MockMessageSenderMockRecorder is the mock recorder for MockMessageSender.
type MockMessageSenderMockRecorder struct {
	mock *MockMessageSender
}

// NewMockMessageSender creates a new mock instance.
func NewMockMessageSender(ctrl *gomock.Controller) *MockMessageSender {
	mock := &MockMessageSender{ctrl: ctrl}
	mock.recorder = &MockMessageSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageSender) EXPECT() *MockMessageSenderMockRecorder {
	return m.recorder
}

// DeleteMessage mocks base method.
func (m *MockMessageSender) DeleteMessage(ctx context.Context, chatID msginfo.ChatID, messageID msginfo.MessageID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteMessage", ctx, chatID, messageID)
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessageSenderMockRecorder) DeleteMessage(ctx, chatID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessageSender)(nil).DeleteMessage), ctx, chatID, messageID)
}

// EditMessage mocks base method.
func (m *MockMessageSender) EditMessage(ctx context.Context, chatID msginfo.ChatID, messageID msginfo.MessageID, text string, rows ...button.ButtonRow) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, chatID, messageID, text}
	for _, a := range rows {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EditMessage", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditMessage indicates an expected call of EditMessage.
func (mr *MockMessageSenderMockRecorder) EditMessage(ctx, chatID, messageID, text any, rows ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, chatID, messageID, text}, rows...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessage", reflect.TypeOf((*MockMessageSender)(nil).EditMessage), varargs...)
}

// EscapeMarkdown mocks base method.
func (m *MockMessageSender) EscapeMarkdown(s string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EscapeMarkdown", s)
	ret0, _ := ret[0].(string)
	return ret0
}

// EscapeMarkdown indicates an expected call of EscapeMarkdown.
func (mr *MockMessageSenderMockRecorder) EscapeMarkdown(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EscapeMarkdown", reflect.TypeOf((*MockMessageSender)(nil).EscapeMarkdown), s)
}

// ReplyMessage mocks base method.
func (m *MockMessageSender) ReplyMessage(ctx context.Context, chatID msginfo.ChatID, replyMessageID msginfo.MessageID, text string, textType messageprocessor.MessageTextType, rows ...button.ButtonRow) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, chatID, replyMessageID, text, textType}
	for _, a := range rows {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReplyMessage", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplyMessage indicates an expected call of ReplyMessage.
func (mr *MockMessageSenderMockRecorder) ReplyMessage(ctx, chatID, replyMessageID, text, textType any, rows ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, chatID, replyMessageID, text, textType}, rows...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplyMessage", reflect.TypeOf((*MockMessageSender)(nil).ReplyMessage), varargs...)
}

// SendMessage mocks base method.
func (m *MockMessageSender) SendMessage(ctx context.Context, chatID msginfo.ChatID, text string, textType messageprocessor.MessageTextType, rows ...button.ButtonRow) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, chatID, text, textType}
	for _, a := range rows {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendMessage", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMessageSenderMockRecorder) SendMessage(ctx, chatID, text, textType any, rows ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, chatID, text, textType}, rows...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMessageSender)(nil).SendMessage), varargs...)
}

// MockTimeProvider is a mock of TimeProvider interface.
type MockTimeProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTimeProviderMockRecorder
	isgomock struct{}
}

// MockTimeProviderMockRecorder is the mock recorder for MockTimeProvider.
type MockTimeProviderMockRecorder struct {
	mock *MockTimeProvider
}

// NewMockTimeProvider creates a new mock instance.
func NewMockTimeProvider(ctrl *gomock.Controller) *MockTimeProvider {
	mock := &MockTimeProvider{ctrl: ctrl}
	mock.recorder = &MockTimeProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeProvider) EXPECT() *MockTimeProviderMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockTimeProvider) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockTimeProviderMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockTimeProvider)(nil).Now))
}
