log_level: "info"
tracing:
  endpoint: "jaeger:4318"
  service_name: "bonus-points-bot"
bot:
  token: "bonus-points-bot-token"
  payment_token: "payment_bot_token"
postgres:
  connection: "host=postgres port=5432 user=bot password=bot dbname=bot sslmode=disable"
button_redis:
  addr: "redis:6379"
  pwd: "redis123"
  db: 1
  ttl: 1h
cart_redis:
  addr: "redis:6379"
  pwd: "redis123"
  db: 2
  ttl: 1h
daily_position_redis:
  addr: "redis:6379"
  pwd: "redis123"
  db: 3
  ttl: 30h
store_id: 1
order_history:
  page_size: 10
